import {
    TwiterIcon,
    CodeIcon,
    FriendIcon,
    LinkIcon,
    FacebookIcon,
    WhatsAppIcon,
    LinkedlnIcon,
    RedditIcon,
    TelegramIcon,
    EmailIcon,
    LineIcon,
    PinterestIcon,
    DownArrowIcon,
} from '~/components/Icons';

export const MENU_SHARED_ITEMS = [
    {
        icon: <CodeIcon />,
        title: 'Embed',
    },
    {
        icon: <FriendIcon />,
        title: 'Send to friends',
    },
    {
        icon: <FacebookIcon />,
        title: 'Share to Facebook',
    },
    {
        icon: <WhatsAppIcon />,
        title: 'Share to WhatsApp',
    },
    {
        icon: <LinkIcon />,
        title: 'Copy link',
    },
    {
        icon: <DownArrowIcon />,
        title: '',
        handleShow: 'ShowMore',
        styles: 'center',
    },
];

export const MENU_SHARED_ITEMS_MORE = [
    {
        icon: <TwiterIcon />,
        title: 'Share to Twiter',
    },
    {
        icon: <LinkedlnIcon />,
        title: 'Share to LinkedIn',
    },
    {
        icon: <RedditIcon />,
        title: 'Share to Reddit',
    },
    {
        icon: <TelegramIcon />,
        title: 'Share to Telegram',
    },
    {
        icon: <EmailIcon />,
        title: 'Share to Email',
    },
    {
        icon: <LineIcon />,
        title: 'Share to Line',
    },
    {
        icon: <PinterestIcon />,
        title: 'Share to Pinterest',
    },
];

export const EMOJI_LIST = [
    { title: '😀' },
    { title: '😃' },
    { title: '😄' },
    { title: '😁' },
    { title: '😆' },
    { title: '😅' },
    { title: '🤣' },
    { title: '😂' },
    { title: '🙂' },
    { title: '🙃' },
    { title: '😉' },
    { title: '😊' },
    { title: '😇' },
    { title: '😍' },
    { title: '😘' },
    { title: '😗' },
    { title: '😚' },
    { title: '😙' },
    { title: '😋' },
    { title: '😛' },
    { title: '😜' },
    { title: '😝' },
    { title: '🤑' },
    { title: '🤗' },
    { title: '🤔' },
    { title: '🤐' },
    { title: '😐' },
    { title: '😑' },
    { title: '😶' },
    { title: '😏' },
    { title: '😒' },
    { title: '🙄' },
    { title: '😬' },
    { title: '🤥' },
    { title: '😌' },
    { title: '😔' },
    { title: '😪' },
    { title: '🤤' },
    { title: '😴' },
    { title: '😷' },
    { title: '🤒' },
    { title: '🤕' },
    { title: '🤢' },
    { title: '🤧' },
    { title: '😵' },
    { title: '🤠' },
    { title: '😎' },
    { title: '🤓' },
    { title: '😕' },
    { title: '😟' },
    { title: '🙁' },
    { title: '😮' },
    { title: '😯' },
    { title: '😲' },
    { title: '😳' },
    { title: '😦' },
    { title: '😧' },
    { title: '😨' },
    { title: '😰' },
    { title: '😥' },
    { title: '😢' },
    { title: '😭' },
    { title: '😱' },
    { title: '😖' },
    { title: '😣' },
    { title: '😞' },
    { title: '😓' },
    { title: '😩' },
    { title: '😫' },
    { title: '😤' },
    { title: '😡' },
    { title: '😠' },
    { title: '😈' },
    { title: '👿' },
    { title: '💀' },
    { title: '💩' },
    { title: '🤡' },
    { title: '👹' },
    { title: '👺' },
    { title: '👻' },
    { title: '👽' },
    { title: '👾' },
    { title: '🤖' },
    { title: '😺' },
    { title: '😸' },
    { title: '😹' },
    { title: '😻' },
    { title: '😼' },
    { title: '😽' },
    { title: '🙀' },
    { title: '😿' },
    { title: '😾' },
];
